### ISSUE TITLE
inductor F.Fab REF** should be inside component box

### ISSUE THREAD

**Issue by jensenr30** [KiCad/Inductors_SMD.pretty#14]
Currently, all of the SMD inductors in this library have their F.Fab **REF**** *outside* their F.Fab boxes:
![image](https://user-images.githubusercontent.com/3083835/28394794-44054bb0-6cb5-11e7-93c4-0611b0c9bfe6.png)

However, all of the SMD resistors have their **REF**** *inside* their boxes:
![image](https://user-images.githubusercontent.com/3083835/28394750-e2c66050-6cb4-11e7-81f7-22e4d3beeecb.png)

I think it would be great to move the **REF**** inside the box for all inductors in this library.

I am willing to go through the work of doing this. I have already forked a repository.
I am waiting for feedback from the people who manage this repo. Does this sound good to other people as well? If I get positive responses, I will go ahead with the work and then make a pull-request.

**Comment by SchrodingersGat** [comment]
This is a good idea, thanks for volunteering :) Such a fix would be welcomed.

**Comment by SchrodingersGat** [comment]
Thanks for sorting this out.

**Comment by jensenr30** [comment]
@SchrodingersGat No problem!
I'll try to look at generating these inductors with the python scripts that have been mentioned in other issues in other kicad modules.
