### ISSUE TITLE
Backslash problem

### ISSUE THREAD

**Issue by alitekin2fx** [KiCad/Inductors_SMD.pretty#17]
Hi guys, backslashes in model names looks like wrong, it needs to be changed to forward slash.
-  (model ${KISYS3DMOD}/Inductors_SMD.3dshapes\L_0603.wrl
+  (model ${KISYS3DMOD}/Inductors_SMD.3dshapes/L_0603.wrl

**Comment by poeschlr** [comment]
Would you care to open a pull request for this?

**Comment by alitekin2fx** [comment]
Hi @poeschlr, i did it.
